/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ShaderFXEffect
@P   - EffectNodeBase.EffectNodeBaseShader: mixin SRgbToLinear_ShaderFX [{SRgb = InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>}]
@P SRgb: InputFloat4<ShaderFX.InputValueFloat4,PerUpdate>
***************************
*****     Sources     *****
***************************
@S    ShaderBase => 01e372056ff6c06edab8e988414a8f75
@S    ShaderBaseStream => 91c0ea8aae0a45ca00578a4084fa3607
@S    SRgbToLinear_ShaderFX => c1818816125e87fc35921cf7ba42a73f
@S    ComputeFloat4 => 6aeb31691af393d622350bb42f15ad31
@S    ColorUtilityTemp => aaad87d7a436b3b45e9357c497e8f2e5
@S    InputFloat4 => dde84bd708e467fe677dfda4ce575339
@S    DeclFloat4 => b2a3d29ab3b24927c9d8403a0245327b
***************************
*****     Stages      *****
***************************
@G    Vertex => 7ae935036a1b3058f70dafa629ea5dea
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
vs_5_0
dcl_globalFlags refactoringAllowed

#line 14 "C:\Users\elektromeier\Desktop\VomAmt\VomAmtVR\lib\log\shader_ShaderFXEffect_60ba71596a887c6f52aa2526170d2ca1.hlsl"
ret 
// Approximately 1 instruction slots used
***************************
*************************/
struct VS_STREAMS 
{
};
struct VS_INPUT 
{
};
cbuffer PerUpdate 
{
    float4 InputValue_id15;
};
void VSMain()
{
    VS_STREAMS streams = (VS_STREAMS)0;
}
