/**************************
***** Compiler Parameters *****
***************************
@P EffectName: RadiancePrefilteringGGXNoComputeEffect
@P   - RadiancePrefilteringGGXNoComputeParams.NbOfSamplings: 1024
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 64]
@C    MatrixTransform_id74 => SpriteBase.MatrixTransform
cbuffer Globals [Size: 96]
@C    Texture0TexelSize_id16 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id18 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id20 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id22 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id24 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id26 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id28 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id30 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id32 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id34 => Texturing.Texture9TexelSize
@C    RadianceMapSize_id76 => RadiancePrefilteringGGXNoComputeShader.RadianceMapSize
@C    MipmapCount_id78 => RadiancePrefilteringGGXNoComputeShader.MipmapCount
@C    Roughness_id79 => RadiancePrefilteringGGXNoComputeShader.Roughness
@C    Face_id80 => RadiancePrefilteringGGXNoComputeShader.Face
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    LinearSampler_id45 => Texturing.LinearSampler [Stage: Pixel, Slot: (0-0)]
@R    RadianceMap_id77 => RadiancePrefilteringGGXNoComputeShader.RadianceMap [Stage: Pixel, Slot: (0-0)]
@R    Globals => Globals [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    RadiancePrefilteringGGXNoComputeShader => 40ef6720b05aca35d51dbfbed69e5c12
@S    Math => 395aa210901b9e0783594d1b4fb0a441
@S    ImageEffectShader => 9b7cefba2dd674808bc791525995b495
@S    SpriteBase => 67b12f03dd9d34e76b6fcfb517afba8c
@S    ShaderBase => 01e372056ff6c06edab8e988414a8f75
@S    ShaderBaseStream => 91c0ea8aae0a45ca00578a4084fa3607
@S    Texturing => 6605f68230266eff2bc8b4e8102ede6b
@S    CubemapUtils => a4c5112e07e607c48973594b7cfccc36
@S    Hammersley => 18b1416e7f503012ece2211e20fec7d3
@S    ImportanceSamplingGGX => 4a97c05328877d9e733a53fd26c65351
@S    BRDFMicrofacet => 634bc8cd641b44251287c32dc4bb310b
***************************
*****     Stages      *****
***************************
@G    Vertex => 79eb7ff071584feaa45b858a38e87b6a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 MatrixTransform_id74;     // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
//
// Initial variable locations:
//   v0.x <- __input__.Position_id73.x; v0.y <- __input__.Position_id73.y; v0.z <- __input__.Position_id73.z; v0.w <- __input__.Position_id73.w; 
//   v1.x <- __input__.TexCoord_id63.x; v1.y <- __input__.TexCoord_id63.y; 
//   o1.x <- <VSMain return value>.TexCoord_id63.x; o1.y <- <VSMain return value>.TexCoord_id63.y; 
//   o0.x <- <VSMain return value>.ShadingPosition_id1.x; o0.y <- <VSMain return value>.ShadingPosition_id1.y; o0.z <- <VSMain return value>.ShadingPosition_id1.z; o0.w <- <VSMain return value>.ShadingPosition_id1.w
//
#line 224 "C:\Users\elektromeier\Desktop\VomAmt\VomAmtVR\lib\log\shader_RadiancePrefilteringGGXNoComputeEffect_8275c76d611a2814d43b83fae801b030.hlsl"
dp4 o0.x, v0.xyzw, cb0[0].xyzw
dp4 o0.y, v0.xyzw, cb0[1].xyzw
dp4 o0.z, v0.xyzw, cb0[2].xyzw
dp4 o0.w, v0.xyzw, cb0[3].xyzw

#line 228
mov o1.xy, v1.xyxx
ret 
// Approximately 6 instruction slots used
@G    Pixel => 413b5c9928df7d64b69f851b58c43aff
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id16;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id18;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id20;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id22;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id24;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id26;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id28;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id30;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id32;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id34;     // Offset:   72 Size:     8 [unused]
//   int RadianceMapSize_id76;          // Offset:   80 Size:     4
//   float MipmapCount_id78;            // Offset:   84 Size:     4
//   float Roughness_id79;              // Offset:   88 Size:     4
//   int Face_id80;                     // Offset:   92 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// LinearSampler_id45                sampler      NA          NA             s0      1 
// RadianceMap_id77                  texture  float4        cube             t0      1 
// Globals                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[6], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texturecube (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 7
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id1.x; v0.y <- __input__.ShadingPosition_id1.y; v0.z <- __input__.ShadingPosition_id1.z; v0.w <- __input__.ShadingPosition_id1.w; 
//   v1.x <- __input__.TexCoord_id63.x; v1.y <- __input__.TexCoord_id63.y; 
//   o0.x <- <PSMain return value>.ColorTarget_id3.x; o0.y <- <PSMain return value>.ColorTarget_id3.y; o0.z <- <PSMain return value>.ColorTarget_id3.z; o0.w <- <PSMain return value>.ColorTarget_id3.w
//
#line 172 "C:\Users\elektromeier\Desktop\VomAmt\VomAmtVR\lib\log\shader_RadiancePrefilteringGGXNoComputeEffect_8275c76d611a2814d43b83fae801b030.hlsl"
if_nz cb0[5].w

#line 174
  ine r0.x, cb0[5].w, l(1)
  if_nz r0.x

#line 180
    ieq r0.xyzw, cb0[5].wwww, l(2, 3, 4, 5)

#line 182
    mad r1.xy, v1.xyxx, l(-2.000000, -2.000000, 0.000000, 0.000000), l(1.000000, 1.000000, 0.000000, 0.000000)
    mov r1.z, l(-1.000000)
    and r1.xyz, r0.wwww, r1.xyzx  // r1.x <- <ConvertTexcoordsNoFlip_id18 return value>.x; r1.y <- <ConvertTexcoordsNoFlip_id18 return value>.y; r1.z <- <ConvertTexcoordsNoFlip_id18 return value>.z
    mad r2.xy, v1.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
    mov r2.z, l(1.000000)
    movc r1.xyz, r0.zzzz, r2.xyzx, r1.xyzx
    mad r2.xz, v1.xxyx, l(2.000000, 0.000000, -2.000000, 0.000000), l(-1.000000, 0.000000, 1.000000, 0.000000)
    mov r2.y, l(-1.000000)
    movc r0.yzw, r0.yyyy, r2.xxyz, r1.xxyz  // r0.y <- <ConvertTexcoordsNoFlip_id18 return value>.x; r0.z <- <ConvertTexcoordsNoFlip_id18 return value>.y; r0.w <- <ConvertTexcoordsNoFlip_id18 return value>.z
    mad r1.xz, v1.xxyx, l(2.000000, 0.000000, 2.000000, 0.000000), l(-1.000000, 0.000000, -1.000000, 0.000000)
    mov r1.y, l(1.000000)
    movc r0.xyz, r0.xxxx, r1.xyzx, r0.yzwy  // r0.x <- <ConvertTexcoordsNoFlip_id18 return value>.x; r0.y <- <ConvertTexcoordsNoFlip_id18 return value>.y; r0.z <- <ConvertTexcoordsNoFlip_id18 return value>.z
  else 
    mov r0.x, l(-1.000000)
    mad r0.yz, v1.yyxy, l(0.000000, -2.000000, 2.000000, 0.000000), l(0.000000, 1.000000, -1.000000, 0.000000)  // r0.x <- <ConvertTexcoordsNoFlip_id18 return value>.x; r0.y <- <ConvertTexcoordsNoFlip_id18 return value>.y; r0.z <- <ConvertTexcoordsNoFlip_id18 return value>.z
  endif 
else 
  mov r0.x, l(1.000000)
  mad r0.yz, v1.yyxy, l(0.000000, -2.000000, -2.000000, 0.000000), l(0.000000, 1.000000, 1.000000, 0.000000)  // r0.x <- <ConvertTexcoordsNoFlip_id18 return value>.x; r0.y <- <ConvertTexcoordsNoFlip_id18 return value>.y; r0.z <- <ConvertTexcoordsNoFlip_id18 return value>.z
endif 

#line 186
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx  // r0.x <- R.x; r0.y <- R.y; r0.z <- R.z

#line 141
mul r0.w, cb0[5].z, cb0[5].z  // r0.w <- a

#line 143
mul r1.x, r0.w, r0.w
mad r0.w, r0.w, r0.w, l(-1.000000)

#line 149
lt r1.y, |r0.z|, l(0.999000)
movc r1.yzw, r1.yyyy, l(0,1.000000,0,0), l(0,0,1.000000,0)  // r1.y <- UpVector.z; r1.z <- UpVector.x; r1.w <- UpVector.y

#line 150
mul r2.xyz, r0.yzxy, r1.yzwy
mad r1.yzw, r1.wwyz, r0.zzxy, -r2.xxyz
dp3 r2.x, r1.yzwy, r1.yzwy
rsq r2.x, r2.x
mul r1.yzw, r1.yyzw, r2.xxxx  // r1.y <- TangentX.x; r1.z <- TangentX.y; r1.w <- TangentX.z

#line 151
mul r2.xyz, r0.zxyz, r1.zwyz
mad r2.xyz, r0.yzxy, r1.wyzw, -r2.xyzx  // r2.x <- TangentY.x; r2.y <- TangentY.y; r2.z <- TangentY.z

#line 197
itof r2.w, cb0[5].x
mul r2.w, r2.w, r2.w
mul r2.w, r2.w, l(6.000000)
div r2.w, l(12.566371), r2.w  // r2.w <- omegaP

#line 189
mov r3.xyzw, l(0,0,0,0)  // r3.x <- prefilteredSample.x; r3.y <- prefilteredSample.y; r3.z <- prefilteredSample.z; r3.w <- prefilteredSample.w
mov r4.x, l(0)  // r4.x <- sampleIndex
loop 
  ige r4.y, r4.x, l(1024)
  breakc_nz r4.y

#line 159
  mov r4.yz, l(0,0,0.500000,0)  // r4.y <- u; r4.z <- p
  mov r4.w, r4.x  // r4.w <- kk
  loop 
    breakc_z r4.w

#line 161
    and r5.x, r4.w, l(1)

#line 162
    add r5.y, r4.z, r4.y  // r5.y <- u
    movc r4.y, r5.x, r5.y, r4.y  // r4.y <- u

#line 163
    mul r4.z, r4.z, l(0.500000)
    ishr r4.w, r4.w, l(1)
  endloop 

#line 164
  itof r4.z, r4.x
  add r4.z, r4.z, l(0.500000)
  mul r4.w, r4.z, l(0.000977)  // r4.w <- v

#line 142
  mul r5.x, r4.y, l(6.283185)  // r5.x <- phi

#line 143
  mad r4.z, -r4.z, l(0.000977), l(1.000000)
  mad r4.w, r0.w, r4.w, l(1.000000)
  div r4.z, r4.z, r4.w
  sqrt r4.z, r4.z  // r4.z <- CosTheta

#line 144
  mad r4.w, -r4.z, r4.z, l(1.000000)
  sqrt r4.w, r4.w  // r4.w <- SinTheta

#line 146
  sincos r5.x, r6.x, r5.x
  mul r5.y, r4.w, r6.x  // r5.y <- H.x

#line 147
  mul r4.w, r4.w, r5.x  // r4.w <- H.y

#line 152
  mul r5.xzw, r2.xxyz, r4.wwww
  mad r5.xyz, r1.yzwy, r5.yyyy, r5.xzwx
  mad r5.xyz, r0.xyzx, r4.zzzz, r5.xyzx  // r5.x <- <GetSample_id20 return value>.x; r5.y <- <GetSample_id20 return value>.y; r5.z <- <GetSample_id20 return value>.z

#line 193
  dp3 r4.z, r0.xyzx, r5.xyzx
  add r4.z, r4.z, r4.z
  mad r5.xyz, r4.zzzz, r5.xyzx, -r0.xyzx  // r5.x <- L.x; r5.y <- L.y; r5.z <- L.z

#line 194
  dp3_sat r6.w, r0.xyzx, r5.xyzx  // r6.w <- NoL

#line 201
  lt r4.z, l(0.000000), r6.w
  if_nz r4.z

#line 136
    mul r4.z, r6.w, r6.w
    mad r4.z, r4.z, r0.w, l(1.000000)
    max r4.z, r4.z, l(0.000100)  // r4.z <- d

#line 137
    mul r4.z, r4.z, r4.z
    mul r4.z, r4.z, l(3.141593)
    div r4.z, r1.x, r4.z  // r4.z <- <NormalDistributionGGX_id21 return value>

#line 196
    mul r4.z, r4.z, l(256.000000)
    div r4.z, l(1.000000, 1.000000, 1.000000, 1.000000), r4.z  // r4.z <- omegaS

#line 198
    div r4.z, r4.z, r2.w
    log r4.z, r4.z
    mul r4.z, r4.z, l(0.500000)
    max r4.z, r4.z, l(0.000000)
    min r4.z, r4.z, cb0[5].y  // r4.z <- mipLevel

#line 204
    sample_l_indexable(texturecube)(float,float,float,float) r5.xyz, r5.xyzx, t0.xyzw, s0, r4.z
    mul r6.xyz, r6.wwww, r5.xyzx  // r6.x <- prefilteredColor.x; r6.y <- prefilteredColor.y; r6.z <- prefilteredColor.z

#line 205
  else   // Prior locations: r5.x <- L.x; r5.y <- L.y; r5.z <- L.z
    mov r6.xyzw, l(0,0,0,0)  // r6.x <- prefilteredColor.x; r6.y <- prefilteredColor.y; r6.z <- prefilteredColor.z
  endif 

#line 206
  add r3.xyzw, r6.xyzw, r3.xyzw

#line 207
  iadd r4.x, r4.x, l(1)
endloop 

#line 208
div o0.xyzw, r3.xyzw, r3.wwww

#line 217
ret 
// Approximately 103 instruction slots used
***************************
*************************/
static const float PI_id0 = 3.14159265358979323846;
const static int TNbOfSamples_id75 = 1024;
struct PS_STREAMS 
{
    float2 TexCoord_id63;
    float4 ColorTarget_id3;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id3 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id1 : SV_Position;
    float2 TexCoord_id63 : TEXCOORD0;
};
struct VS_STREAMS 
{
    float4 Position_id73;
    float2 TexCoord_id63;
    float4 ShadingPosition_id1;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id1 : SV_Position;
    float2 TexCoord_id63 : TEXCOORD0;
};
struct VS_INPUT 
{
    float4 Position_id73 : POSITION;
    float2 TexCoord_id63 : TEXCOORD0;
};
cbuffer PerDraw 
{
    float4x4 MatrixTransform_id74;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id16;
    float2 Texture1TexelSize_id18;
    float2 Texture2TexelSize_id20;
    float2 Texture3TexelSize_id22;
    float2 Texture4TexelSize_id24;
    float2 Texture5TexelSize_id26;
    float2 Texture6TexelSize_id28;
    float2 Texture7TexelSize_id30;
    float2 Texture8TexelSize_id32;
    float2 Texture9TexelSize_id34;
    int RadianceMapSize_id76;
    float MipmapCount_id78;
    float Roughness_id79;
    int Face_id80;
};
Texture2D Texture0_id15;
Texture2D Texture1_id17;
Texture2D Texture2_id19;
Texture2D Texture3_id21;
Texture2D Texture4_id23;
Texture2D Texture5_id25;
Texture2D Texture6_id27;
Texture2D Texture7_id29;
Texture2D Texture8_id31;
Texture2D Texture9_id33;
TextureCube TextureCube0_id35;
TextureCube TextureCube1_id36;
TextureCube TextureCube2_id37;
TextureCube TextureCube3_id38;
Texture3D Texture3D0_id39;
Texture3D Texture3D1_id40;
Texture3D Texture3D2_id41;
Texture3D Texture3D3_id42;
SamplerState Sampler_id43;
SamplerState PointSampler_id44 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id45 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id46 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id47 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id48 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id49 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id50 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id51 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id52 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id53;
SamplerState Sampler1_id54;
SamplerState Sampler2_id55;
SamplerState Sampler3_id56;
SamplerState Sampler4_id57;
SamplerState Sampler5_id58;
SamplerState Sampler6_id59;
SamplerState Sampler7_id60;
SamplerState Sampler8_id61;
SamplerState Sampler9_id62;
TextureCube RadianceMap_id77;
float NormalDistributionGGX_id21(float alphaR, float nDotH)
{
    float alphaR2 = alphaR * alphaR;
    float d = max(nDotH * nDotH * (alphaR2 - 1) + 1, 0.0001);
    return alphaR2 / (PI_id0 * d * d);
}
float3 GetSample_id20(float2 xi, float roughness, float3 N)
{
    float a = roughness * roughness;
    float phi = 2 * PI_id0 * xi.x;
    float CosTheta = sqrt((1 - xi.y) / (1 + (a * a - 1) * xi.y));
    float SinTheta = sqrt(1 - CosTheta * CosTheta);
    float3 H;
    H.x = SinTheta * cos(phi);
    H.y = SinTheta * sin(phi);
    H.z = CosTheta;
    float3 UpVector = abs(N.z) < 0.999 ? float3(0, 0, 1) : float3(1, 0, 0);
    float3 TangentX = normalize(cross(UpVector, N));
    float3 TangentY = cross(N, TangentX);
    return TangentX * H.x + TangentY * H.y + N * H.z;
}
float2 GetSamplePlane_id19(int k, int samplesCount)
{
    float u = 0.0;
    float p = 0.5;

    for (int kk = k; kk; p *= 0.5, kk >>= 1)
    {
        if (kk & 1)
            u += p;
    }
    float v = (k + 0.5) / samplesCount;
    return float2(u, v);
}
float3 ConvertTexcoordsNoFlip_id18(float2 inputTexcoord, int viewIndex)
{
    float2 position = 2 * inputTexcoord - 1;
    if (viewIndex == 0)
        return float3(1, -position.y, -position.x);
    if (viewIndex == 1)
        return float3(-1, -position.y, position.x);
    if (viewIndex == 2)
        return float3(position.x, 1, position.y);
    if (viewIndex == 3)
        return float3(position.x, -1, -position.y);
    if (viewIndex == 4)
        return float3(position.x, -position.y, 1);
    if (viewIndex == 5)
        return float3(-position.x, -position.y, -1);
    return 0;
}
float4 Shading_id17(inout PS_STREAMS streams)
{
    float3 R = normalize(ConvertTexcoordsNoFlip_id18(streams.TexCoord_id63, Face_id80));
    float4 prefilteredSample = 0;

    for (int sampleIndex = 0; sampleIndex < TNbOfSamples_id75; sampleIndex++)
    {
        float2 xi = GetSamplePlane_id19(sampleIndex, TNbOfSamples_id75);
        float3 H = GetSample_id20(xi, Roughness_id79, R);
        float3 L = 2 * dot(R, H) * H - R;
        float NoL = saturate(dot(R, L));
        float pdf = NormalDistributionGGX_id21(Roughness_id79 * Roughness_id79, NoL) / 4;
        float omegaS = 1.0 / (TNbOfSamples_id75 * pdf);
        float omegaP = 4.0 * PI_id0 / (6.0 * RadianceMapSize_id76 * RadianceMapSize_id76);
        float mipLevel = clamp(0.5 * log2(omegaS / omegaP), 0, MipmapCount_id78);
        float3 prefilteredColor = 0;
        float weight = 0;
        if (NoL > 0)
        {
            weight = NoL;
            prefilteredColor = RadianceMap_id77.SampleLevel(LinearSampler_id45, L, mipLevel).rgb * weight;
        }
        prefilteredSample += float4(prefilteredColor, weight);
    }
    return prefilteredSample / prefilteredSample.w;
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.TexCoord_id63 = __input__.TexCoord_id63;
    streams.ColorTarget_id3 = Shading_id17(streams);
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id3 = streams.ColorTarget_id3;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id73 = __input__.Position_id73;
    streams.TexCoord_id63 = __input__.TexCoord_id63;
    streams.ShadingPosition_id1 = mul(streams.Position_id73, MatrixTransform_id74);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id1 = streams.ShadingPosition_id1;
    __output__.TexCoord_id63 = streams.TexCoord_id63;
    return __output__;
}
